language: python
python:
  - "2.7"
env:
  - TOXENV="py27-django13"
  - TOXENV="py27-django14"
  - TOXENV="py27-django15"
  - TOXENV="py27-django16"
  - TOXENV="py33-django15"
  - TOXENV="py33-django16"
install: pip install tox
script: tox -e $TOXENV
